version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - "> 5.10.0, < 6"
  - dependency-name: webpack
    versions:
    - ">= 5.a, < 6"
  - dependency-name: material-ui-popup-state
    versions:
    - 1.7.2
    - 1.8.0
    - 1.8.2
  - dependency-name: cypress
    versions:
    - 6.6.0
    - 6.7.0
    - 6.7.1
    - 6.8.0
    - 7.0.0
    - 7.0.1
    - 7.1.0
  - dependency-name: next-seo
    versions:
    - 4.20.0
    - 4.22.0
    - 4.23.0
  - dependency-name: nodemailer
    versions:
    - 6.4.17
    - 6.4.18
    - 6.5.0
  - dependency-name: react
    versions:
    - 17.0.1
  - dependency-name: next
    versions:
    - 10.0.5
    - 10.0.6
  - dependency-name: axios
    versions:
    - 0.21.1
  - dependency-name: responsive-loader
    versions:
    - 2.3.0
  - dependency-name: "@material-ui/lab"
    versions:
    - 4.0.0-alpha.57
