version: "3"
services:
  livinglab-site-v3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 10002:3000
    restart: always
    expose:
    - "3000"
    environment:
        - .env
    stdin_open: true # docker run -i
    tty: true        # docker run -t