site_name: Living Lab Website Documentation
copyright: Copyright System Health Lab 2020
author: Frinze Erin Lapuz
author_website: https://frinzelapuz.vercel.app
repo_url: https://github.com/uwasystemhealth/livinglab-site-v3
theme:
  name: material
  custom_dir: overrides
  palette:
    primary: orange
    scheme: slate # "slate" is dark, "default" is white
  logo: images/docs.png
  favicon: images/docs.png
  # features:
  #   - navigation.tabs
plugins:
  - search
  - mermaid2:
      version: 8.8.2
      arguments:
        theme: dark # white | dark

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.smartsymbols
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
  - pymdownx.tabbed
  - footnotes
  - pymdownx.critic
  - attr_list
  - def_list
  - pymdownx.tasklist
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
      toc_depth: 4
  - codehilite
  - pymdownx.snippets:
      base_path: docs
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid

extra_javascript:
  - https://unpkg.com/mermaid@8.8.2/dist/mermaid.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
- Overview: index.md